### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Apatt7882** [qbcore-framework/qb-shops#140]
**Describe the bug**
My stores will not restock. Even after taking the server down and restarting it. This is the only _restock_ I've found in any of the lua's. 

**Expected behavior**
I would like it to automatically restock when you get out of the menu or at least on a consistant basis.

**Screenshots**
![image](https://user-images.githubusercontent.com/118646120/202881425-7823176c-8584-4327-8a25-8defdc4f678c.png)

**Questions (please complete the following information):**
I'm just getting into the server building process, the server is the latest QBCore build that's on the fivem server creator option.
Not other than vehicles/eup.
 - Have you renamed `qb-` to something custom? No.

**Comment by CrazyDevelopment** [comment]
In your qb-shops > server.lua around line 15 you should see this  ->
if not shop or not Config.Locations[shop]?["products"] then return end

Remove the question mark. so that it looks like this - > 
if not shop or not Config.Locations[shop]["products"] then return end

My guess is someone had happy fingers that day XD 
Hope this helps
